### ISSUE TITLE
Add output option to README

### ISSUE THREAD

**Issue by Guseyn** [obedm503/katex-latex#44]
In order to avoid confusion, it's better to mention output option in README:

```
{
        displayMode: true,
        throwOnError: false, // allows katex to fail silently
        errorColor: '#ff0000',
        delimiters: [
          { left: '$$', right: '$$', display: false },
          { left: '~', right: '~', display: false, asciimath: true },
        ],
        output: 'mathml'
}
```

Otherwise I am getting duplicate output in html and mathml, which is weird. 

Here is the docs on this option: https://katex.org/docs/options.html

**Comment by obedm503** [comment]
You're getting duplicate output because katex's default `output` value is `htmlAndMathml`. `showdown-katex` is simply a wrapper, and so `options` get passed straight into katex.

From the katex docs:
![image](https://github.com/obedm503/showdown-katex/assets/9118707/bfd7ff9a-588b-473e-b860-c31c3d3fc827)


Thanks for the suggestion but this is unnecessary.
